derive: fix compilation error if user define its own Result type
ironthree/dxr pull request #20
Opened 2024-07-11 20:39 UTC by abernardeau-wallix

When using the `TryFromValue` and `TryToValue` macros in a file where a custom `Result` is defined (in my case `
type Result<T> = std::result::Result<T, Box<dyn Error + Send + Sync>>;`) the macro doesn't work anymore and create a compilation error.

The Result seems to be common pattern and I think it should not break the macrso (https://doc.rust-lang.org/rust-by-example/error/result/result_alias.html )

2024-07-11 21:03 UTC, decathorpe commented on dxr_derive/src/lib.rs
> +            fn try_from_value(value: &#dxr::Value) -> std::result::Result<#name #ty_generics, #dxr::DxrError> {
Can you replace this with `::std::result::Result`, similar to other `std` imports?

2024-07-11 21:03 UTC, decathorpe commented on dxr_derive/src/lib.rs
> +            fn try_to_value(&self) -> std::result::Result<#dxr::Value, #dxr::DxrError> {
Same thing applies here.

2024-07-11 21:04 UTC, decathorpe requested changes
Thank you, this looks mostly good to me, with two minor issues.

(Imagine somebody redefining `std`, it would cause the same problem as the custom `Result`.)

2024-07-11 21:11 UTC, decathorpe commented
Great, thanks! Let's see what the CI says.

2024-07-11 21:12 UTC, abernardeau-wallix commented
I updated the PR with your wise remarks. 

>(Imagine somebody redefining `std`, it would cause the same problem as the custom `Result`.)
This is a terrifying thought 😱.

2024-07-12 09:07 UTC, abernardeau-wallix commented
It seems that the nightly jobs is failing to the `time` crate used here not being compatible with the nightly toolchain.
Locally running a cargo update seems to be fixing the issue but it updates a bunch of dependencies.

2024-07-12 10:20 UTC, decathorpe commented
Awesome. Thank you for the contribution!

2024-07-12 10:20 UTC, merged

2024-07-12 10:21 UTC, decathorpe commented
Do you need a new release in the v0.6 branch with this fix? Or would it be OK if this just ends up in 0.7.0?

2024-07-12 10:27 UTC, abernardeau-wallix commented
If it's not too much work I would be happy to have a release with the fix but I can implement a workaround in my code and can wait for the 0.7.0 version.
Thank you for the nice library and your reactivity.

2024-07-12 13:48 UTC, decathorpe commented
I'm working on some refactors for 0.7.0 still, so I'll cherry-pick your change onto the v0.6 release series and publish a new version.